package com.sorcery.utils;


public enum MonolithData
{

    CHISELED("chiseled", new InterferencePattern.PatternBuilder()
            .addLine("-----------------")
            .addLine("------NNNNN------")
            .addLine("----NN-----NN----")
            .addLine("---N---NNN---N---")
            .addLine("--N--NN---NN--N--")
            .addLine("--N-N--NNN--N-N--")
            .addLine("-N--N-N---N-N--N-")
            .addLine("-N-N-N-NNN-N-N-N-")
            .addLine("-N-N-N-NIN-N-N-N-")
            .addLine("-N-N-N-NNN-N-N-N-")
            .addLine("-N--N-N---N-N--N-")
            .addLine("--N-N--NNN--N-N--")
            .addLine("--N--NN---NN--N--")
            .addLine("---N---NNN---N---")
            .addLine("----NN-----NN----")
            .addLine("------NNNNN------")
            .addLine("-----------------")
            .build()
    ),
    DARK("dark", new InterferencePattern.PatternBuilder()
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("--------I--------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .build()
    ),
    LAPIS("lapis", new InterferencePattern.PatternBuilder()
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("--------I--------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .build()
    ),
    LUNAR("lunar", new InterferencePattern.PatternBuilder()
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("--------I--------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .addLine("-----------------")
            .build()
    ),
    SOLAR("solar", new InterferencePattern.PatternBuilder()
            .addLine("N-------N-------N")
            .addLine("-N------N------N-")
            .addLine("--N-----N-----N--")
            .addLine("---N----N----N---")
            .addLine("----N---N---N----")
            .addLine("-----N--N--N-----")
            .addLine("------N-N-N------")
            .addLine("-------NNN-------")
            .addLine("NNNNNNNNINNNNNNNN")
            .addLine("-------NNN-------")
            .addLine("------N-N-N------")
            .addLine("-----N--N--N-----")
            .addLine("----N---N---N----")
            .addLine("---N----N----N---")
            .addLine("--N-----N-----N--")
            .addLine("-N------N------N-")
            .addLine("N-------N-------N")
            .build()
    );


    private final String name;
    public final InterferencePattern pattern;

    private MonolithData(String name, InterferencePattern pattern)
    {
        this.name = name;
        this.pattern = pattern;
    }
}
